CREATE TABLE sector (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(10) NOT NULL,
  base_price DECIMAL(10,2) NOT NULL,
  max_capacity INT NOT NULL,
  open_hour TIME NOT NULL,
  close_hour TIME NOT NULL,
  duration_limit_minutes INT NOT NULL,
  current_occupancy INT DEFAULT 0,
  is_open BOOLEAN DEFAULT TRUE
);

CREATE TABLE parking_spot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sector_id BIGINT NOT NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  CONSTRAINT fk_parking_spot_sector FOREIGN KEY (sector_id) REFERENCES sector(id)
);

CREATE TABLE billing_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_plate VARCHAR(10) NOT NULL,
  sector_id BIGINT NOT NULL,
  entry_time TIMESTAMP NOT NULL,
  exit_time TIMESTAMP NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'BRL',
  CONSTRAINT fk_billing_sector FOREIGN KEY (sector_id) REFERENCES sector(id)
);

CREATE TABLE vehicle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_plate VARCHAR(10) NOT NULL UNIQUE,
  entry_time TIMESTAMP NOT NULL,
  exit_time TIMESTAMP,
  parked_time TIMESTAMP,
  spot_id BIGINT,
  sector_id BIGINT,
  current_price DECIMAL(10,2) DEFAULT 0.00,
  CONSTRAINT fk_vehicle_spot FOREIGN KEY (spot_id) REFERENCES parking_spot(id),
  CONSTRAINT fk_vehicle_sector FOREIGN KEY (sector_id) REFERENCES sector(id)
);

INSERT INTO sector (name, base_price, max_capacity, open_hour, close_hour, duration_limit_minutes, current_occupancy, is_open)
VALUES ('A', 10.00, 10, '08:00:00', '22:00:00', 240, 9, true);

INSERT INTO parking_spot (sector_id, latitude, longitude)
VALUES (1, -23.5616840, -46.6559810),
       (1, -24.5616840, -46.6559810);

INSERT INTO billing_record (license_plate, sector_id, entry_time, exit_time, amount, currency)
VALUES ('ZUL0001', 1, '2025-01-02 12:00:00', '2025-01-02 13:00:00', 12.75, 'BRL');

INSERT INTO vehicle (
  license_plate,
  entry_time,
  exit_time,
  parked_time,
  spot_id,
  sector_id,
  current_price
) VALUES (
  'ZUL0001',
  '2025-01-02 12:00:00',
  '2025-01-02 12:05:00',
  '2025-01-02 13:00:00',
  2,
  1,
  12.75
);